# Generated by Django 4.1.3 on 2022-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
